Repository project-redhead/redhead, pull requests merged in 2019-07, with the labels that each got.

#38 Add Kummerkasten, Time Table and Train Schedule
  .idea/vcs.xml
  src/main/src/xyz/dommi/beans/SuggestionBean.java
  src/main/src/xyz/dommi/db/SuggestionDB.java
  src/main/webapp/assets/css/_redhead.css
  src/main/webapp/assets/css/lists.css
  src/main/webapp/assets/js/common/http-service.js
  src/main/webapp/assets/js/index.js
  src/main/webapp/bahn.jsp
  src/main/webapp/index.jsp
  src/main/webapp/schedule.jsp
  src/main/webapp/suggestions.jsp
Labels: enhancement, feature

#43 Add first iteration of Bets to Front End
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/beans/UserBean.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/requests/RequestManager.class
  src/main/src/xyz/dommi/beans/BetGameBean.java
  src/main/src/xyz/dommi/db/UserDB.java
  src/main/webapp/assets/css/buttons.css
  src/main/webapp/assets/css/lists.css
  src/main/webapp/assets/js/common/http-service.js
  src/main/webapp/assets/js/index.js
  src/main/webapp/bets.jsp
  src/main/webapp/index.jsp
Labels: feature

#45 Add Games to Front End
  src/main/webapp/assets/css/_redhead.css
  src/main/webapp/assets/css/buttons.css
  src/main/webapp/assets/css/cards.css
  src/main/webapp/assets/css/forms.css
  src/main/webapp/assets/css/lists.css
  src/main/webapp/assets/js/common/http-service.js
  src/main/webapp/bets.jsp
  src/main/webapp/index.jsp
Labels: enhancement, feature

#48 Add Sidebar
  src/main/src/xyz/dommi/db/DBConnection.java
  src/main/webapp/assets/css/_redhead.css
  src/main/webapp/assets/css/sidebar.css
  src/main/webapp/assets/js/_sidebar.js
  src/main/webapp/assets/js/common/http-service.js
  src/main/webapp/assets/vendor/blueprint.min.css
  src/main/webapp/assets/vendor/flexboxgrid.min.css
  src/main/webapp/bets.jsp
  src/main/webapp/index.jsp
  src/main/webapp/suggestions.jsp
Labels: enhancement, feature

#49 Feature/javadoc
  .idea/encodings.xml
  .idea/vcs.xml
  src/main/src/xyz/dommi/beans/BetBean.java
  src/main/src/xyz/dommi/beans/BetGameBean.java
  src/main/src/xyz/dommi/beans/SuggestionBean.java
  src/main/src/xyz/dommi/beans/UserBean.java
  src/main/src/xyz/dommi/common/DiscordWebhook.java
  src/main/src/xyz/dommi/common/EnvironmentConfig.java
  src/main/src/xyz/dommi/common/HttpUtils.java
  src/main/src/xyz/dommi/common/MensaAPI.java
  src/main/src/xyz/dommi/requests/Request.java
  src/main/src/xyz/dommi/requests/RequestManager.java
  src/main/src/xyz/dommi/requests/Response.java
  src/main/src/xyz/dommi/requests/bean/BeanRequest.java
  src/main/src/xyz/dommi/requests/bean/BetBeanRequest.java
  src/main/src/xyz/dommi/requests/bean/BetGameBeanRequest.java
  src/main/src/xyz/dommi/requests/bean/SuggestionBeanRequest.java
  src/main/src/xyz/dommi/requests/bean/UserBeanRequest.java
  src/main/src/xyz/dommi/requests/json/BetInfo.java
  src/main/src/xyz/dommi/requests/json/ClaimReward.java
  src/main/src/xyz/dommi/requests/json/CreateBet.java
  src/main/src/xyz/dommi/requests/json/CreateGame.java
  src/main/src/xyz/dommi/requests/json/CreateSuggestion.java
  src/main/src/xyz/dommi/requests/json/GameInfo.java
  src/main/src/xyz/dommi/requests/json/GameList.java
  src/main/src/xyz/dommi/requests/json/GetMealToday.java
  src/main/src/xyz/dommi/requests/json/JsonRequest.java
  src/main/src/xyz/dommi/requests/json/SetAnswer.java
  src/main/src/xyz/dommi/requests/json/SetSuggestionRead.java
  src/main/src/xyz/dommi/requests/json/SuggestionInfo.java
  src/main/src/xyz/dommi/requests/json/UserInfo.java
  src/main/src/xyz/dommi/servlets/LoginServlet.java
  src/main/src/xyz/dommi/servlets/LoginSuccessServlet.java
  src/main/src/xyz/dommi/servlets/RequestServlet.java
  src/main/src/xyz/dommi/servlets/UserServlet.java
  src/main/webapp/beantest.jsp
  src/main/webapp/sandbox.jsp
Labels: feature

#51 Auth, CSS polishing
  src/main/webapp/assets/css/sidebar.css
  src/main/webapp/assets/css/widgets.css
  src/main/webapp/assets/js/_auth.js
  src/main/webapp/assets/js/index.js
  src/main/webapp/bets.jsp
  src/main/webapp/index.jsp
  src/main/webapp/suggestions.jsp
Labels: enhancement

#52 Add latest game to index.jsp
  src/main/webapp/assets/js/common/http-service.js
  src/main/webapp/assets/js/index.js
  src/main/webapp/index.jsp
Labels: enhancement

#53 Add sidebar to schedule.jsp
  src/main/webapp/assets/css/_redhead.css
  src/main/webapp/assets/css/alerts.css
  src/main/webapp/assets/js/_sidebar.js
  src/main/webapp/assets/js/_wip.js
  src/main/webapp/assets/js/index.js
  src/main/webapp/bahn.jsp
  src/main/webapp/bets.jsp
  src/main/webapp/index.jsp
  src/main/webapp/schedule.jsp
Labels: enhancement
