Repository project-redhead/redhead, pull requests merged in 2019-06, with the labels that each got.

#7 Feature/mongodb
  .gitignore
  .idea/misc.xml
  .idea/workspace.xml
  bin/.gitignore
  bin/.idea/misc.xml
  bin/.idea/workspace.xml
  bin/lib/javax.annotation.jar
  bin/lib/javax.ejb.jar
  bin/lib/javax.jms.jar
  bin/lib/javax.persistence.jar
  bin/lib/javax.resource.jar
  bin/lib/javax.servlet.jar
  bin/lib/javax.servlet.jsp.jar
  bin/lib/javax.servlet.jsp.jstl.jar
  bin/lib/javax.transaction.jar
  bin/pom.xml
  bin/src/main/src/xyz/dommi/db/BetGameDB.class
  bin/src/main/src/xyz/dommi/db/DBConnection.class
  bin/src/main/src/xyz/dommi/db/DBManager.class
  bin/src/main/src/xyz/dommi/db/UserDB.class
  bin/target/DHBWProject.war
  pom.xml
  src/main/src/xyz/dommi/db/BetGameDB.java
  src/main/src/xyz/dommi/db/DBConnection.java
  src/main/src/xyz/dommi/db/DBManager.java
  src/main/src/xyz/dommi/db/UserDB.java
  src/main/src/xyz/dommi/servlets/BetServlet.java
  src/main/src/xyz/dommi/servlets/LoginSuccessServlet.java
  src/main/src/xyz/dommi/servlets/UserRequestServlet.java
  src/main/webapp/index.jsp
  target/DHBWProject.war
  target/DHBWProject/WEB-INF/classes/xyz/dommi/beans/UserBean.class
  target/DHBWProject/WEB-INF/classes/xyz/dommi/db/BetGameDB.class
  target/DHBWProject/WEB-INF/classes/xyz/dommi/db/DBConnection.class
  target/DHBWProject/WEB-INF/classes/xyz/dommi/db/DBManager.class
  target/DHBWProject/WEB-INF/classes/xyz/dommi/db/UserDB.class
  target/DHBWProject/WEB-INF/classes/xyz/dommi/servlets/LoginServlet.class
  target/DHBWProject/WEB-INF/classes/xyz/dommi/servlets/LoginSuccessServlet.class
  target/DHBWProject/WEB-INF/classes/xyz/dommi/servlets/UserServlet.class
  target/DHBWProject/WEB-INF/lib/json-20171018.jar
  target/DHBWProject/WEB-INF/lib/mariadb-java-client-2.4.1.jar
  target/DHBWProject/index.jsp
Labels: feature

#12 Set up CI with Azure Pipelines
  README.md
  azure-pipelines.yml
Labels: enhancement

#17 Add Dockerfile
  Dockerfile
Labels: devops, enhancement

#18 Add Docker build support for Azure Pipelines CI
  azure-pipelines.yml
Labels: devops

#26 Move configuration to environment variables
  src/main/src/xyz/dommi/common/EnvironmentConfig.java
  src/main/src/xyz/dommi/db/DBConnection.java
  src/main/src/xyz/dommi/servlets/LoginServlet.java
Labels: enhancement

#28 Add JWT authorization
  lib/apache-tomcat-9.0.21/webapps/ROOT/META-INF/MANIFEST.MF
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/beans/UserBean.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/db/DBConnection.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/requests/BetInfo.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/requests/CreateBet.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/requests/CreateGame.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/requests/GameInfo.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/requests/GameList.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/requests/Request.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/requests/RequestManager.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/requests/SetAnswer.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/requests/UserInfo.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/servlets/LoginServlet.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/servlets/LoginSuccessServlet.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/servlets/RequestServlet.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/classes/xyz/dommi/servlets/UserServlet.class
  lib/apache-tomcat-9.0.21/webapps/ROOT/WEB-INF/lib/OAuth2Discord--4fded51caa-1.jar
  lib/apache-tomcat-9.0.21/webapps/ROOT/index.jsp
  pom.xml
  src/main/src/xyz/dommi/beans/BetBean.java
  src/main/src/xyz/dommi/beans/BetGameBean.java
  src/main/src/xyz/dommi/beans/UserBean.java
  src/main/src/xyz/dommi/common/HttpUtils.java
  src/main/src/xyz/dommi/db/DBConnection.java
  src/main/src/xyz/dommi/requests/RequestManager.java
  src/main/src/xyz/dommi/requests/bean/BetGameBeanRequest.java
  src/main/src/xyz/dommi/requests/bean/UserBeanRequest.java
  src/main/src/xyz/dommi/requests/json/BetInfo.java
  src/main/src/xyz/dommi/requests/json/CreateBet.java
  src/main/src/xyz/dommi/requests/json/CreateGame.java
  src/main/src/xyz/dommi/requests/json/GameInfo.java
  src/main/src/xyz/dommi/requests/json/GameList.java
  src/main/src/xyz/dommi/requests/json/SetAnswer.java
  src/main/src/xyz/dommi/requests/json/UserInfo.java
  src/main/src/xyz/dommi/servlets/LoginSuccessServlet.java
  src/main/src/xyz/dommi/servlets/UserServlet.java
  src/main/webapp/index.jsp
Labels: enhancement
